### ISSUE TITLE
Where is the definition of the geometry description language?

### ISSUE THREAD

**Issue by foldl** [google-deepmind/alphageometry#11]

**Comment by Respho** [comment]
The Nature article describes it: GEX, JGEX, MMP/Geometer and GeoLogic. The PDF version of the article has the list of operators.

**Comment by Respho** [comment]
It was described in the Nature article, the PDF version has extra details. GE, JGEX, MMP/Geometer and GeoLogic. There is also a list of the operators.

**Comment by foldl** [comment]
@Respho Got it. Thanks.
