### ISSUE TITLE
maybe a wrong rule?

### ISSUE THREAD

**Issue by Noxlgoldi** [google-deepmind/alphageometry#34]
<img width="324" alt="Bildschirmfoto 2024-01-21 um 09 13 10" src="https://github.com/google-deepmind/alphageometry/assets/155834201/12269018-6909-4f93-a5e8-a38edfdef276">

the programm said, that in this case angle JIH = angle JKH

**Comment by geometer** [comment]
They use a non-traditional approach to the angle notation: "angle JIH" means "the angle between straight lines JI and IH". In this sense, the equality is correct. That is discussed in #17

**Comment by Noxlgoldi** [comment]
> They use a non-traditional approach to the angle notation: "angle JIH" means "the angle between straight lines JI and IH". In this sense, the equality is correct. That is discussed in #17

Why does that change anything?

**Comment by sonnguyenasu** [comment]
You can refer to a tutorial about full, oriented, directed angle [here](https://brilliant.org/wiki/directed-angles/)
They use this directed angle so the statement is correct.
