### ISSUE TITLE
ModuleNotFoundError: No module named 'transformer'

### ISSUE THREAD

**Issue by jacubero** [google-deepmind/alphageometry#40]
When running "python alphageometry_test.py", I get the following error:

_Traceback (most recent call last):
  File "/content/alphageometry_test.py", line 21, in <module>
    import alphageometry
  File "/content/alphageometry.py", line 28, in <module>
    import lm_inference as lm
  File "/content/lm_inference.py", line 20, in <module>
    import models  # pylint: disable=unused-import
  File "/content/models.py", line 20, in <module>
    import decoder_stack
  File "/content/decoder_stack.py", line 21, in <module>
    from transformer import decoder_stack
ModuleNotFoundError: No module named 'transformer'_

The same happens with "python lm_inference_test.py --meliad_path=$MELIAD_PATH --data_path=$DATA"

**Comment by Noxlgoldi** [comment]
I got the same error,

Just restart the venv

**Comment by ikrukov** [comment]
> When running "python alphageometry_test.py", I get the following error:
> 
> _Traceback (most recent call last): File "/content/alphageometry_test.py", line 21, in import alphageometry File "/content/alphageometry.py", line 28, in import lm_inference as lm File "/content/lm_inference.py", line 20, in import models # pylint: disable=unused-import File "/content/models.py", line 20, in import decoder_stack File "/content/decoder_stack.py", line 21, in from transformer import decoder_stack ModuleNotFoundError: No module named 'transformer'_
> 
> The same happens with "python lm_inference_test.py --meliad_path=$MELIAD_PATH --data_path=$DATA"

Just make sure meliad_lib/meliad in your PYTHONPATH like it's done here: https://github.com/google-deepmind/alphageometry/blob/a8a1dc70818c1253b6524d761510a6ec6df39c07/run.sh#L31
