### ISSUE TITLE
Tranformation from geogebra to the geometric Language

### ISSUE THREAD

**Issue by Noxlgoldi** [google-deepmind/alphageometry#43]
The geometric language is a real mess. Just a suggestion. Can someone code a geogebra code or chatgpt so thst you can tranform normal language or geogebra into the geometry Language. 

Thank you

**Comment by unhandyandy** [comment]
Bump.

It would be really helpful to have some explanation of the geometric language.  It seems based on GEX, ... but different.

**Comment by hxypqr** [comment]
geogebra code is encoded based on coordinates. To convert it into geometric language, you need to do something similar to SAT resolution
