### ISSUE TITLE
ERROR: No matching distribution found for jaxlib==0.4.6

### ISSUE THREAD

**Issue by michael753-yen** [google-deepmind/alphageometry#51]
When I was running the `$ pip install --require-hashes -r requirements.txt`, it suddenly encountered an error:
`ERROR: Could not find a version that satisfies the requirement jaxlib==0.4.6 (from versions: 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23)
ERROR: No matching distribution found for jaxlib==0.4.6`

I also tried to install it individually but the same error still occured

Or perhaps I can install it from [jaxlib-v0.4.6 github](https://github.com/google/jax/releases/tag/jaxlib-v0.4.6)?

**Comment by Landau1994** [comment]
https://github.com/google-deepmind/alphageometry/issues/13#issuecomment-1901724995

**Comment by michael753-yen** [comment]
@Landau1994 I've read the #13 
the jaxlib lib wheels from https://storage.googleapis.com/jax-releases/jax_cuda_releases.html are all for linux, but I'm trying to run on windows(bash commands were run in git bash)

I find this https://storage.googleapis.com/jax-releases/jax_releases.html which has supported more jaxlib version, unfortunately the oldest version for windows is `0.4.13` so I am still unable to install it
 
Good news is that there is `version 0.4.6` for **macos** users

**Comment by grshennan** [comment]
Same

**Comment by PayteR** [comment]
> @Landau1994 I've read the #13 the jaxlib lib wheels from https://storage.googleapis.com/jax-releases/jax_cuda_releases.html are all for linux, but I'm trying to run on windows(bash commands were run in git bash)
> 
> I find this https://storage.googleapis.com/jax-releases/jax_releases.html which has supported more jaxlib version, unfortunately the oldest version for windows is `0.4.13` so I am still unable to install it
> 
> Good news is that there is `version 0.4.6` for **macos** users

I managed to install `requirements.txt` by removing all hashes and all package versions, but I can't run it on windows anyway due more other issues involved. I think there is no point to push it to run directly on Windows and I will just try to run it via WSL. But here are requirements for you if you are still interested:
```
absl-py
array-record
astunparse
babel
beautifulsoup4
cached-property
cachetools
certifi
charset-normalizer
chex
click
clu
colorama
commonmark
contextlib2
contourpy
cycler
dm-tree
docstring-parser
editdistance
etils[array-types,enp,epath,epy,etqdm,etree]
filelock
flatbuffers
flax
fonttools
fsspec
future
gast
gdown
gin
gin-config
google-auth
google-auth-oauthlib
google-pasta
googleapis-common-protos
grpcio
h5py
huggingface-hub
idna
immutabledict
importlib-resources
jax
jaxlib
joblib
keras
kiwisolver
libclang
lxml
markdown
markupsafe
matplotlib
mesh-tensorflow[transformer]
ml-collections
msgpack
nltk
numpy
oauthlib
opt-einsum
optax
packaging
pandas
pillow
portalocker
promise
protobuf
psutil
pyasn1
pyasn1-modules
pyglove
pygments
pyparsing
pysocks
python-dateutil
pytz
pyyaml
regex
requests[socks]
requests-oauthlib
rich
rouge-score
rsa
sacrebleu
safetensors
scikit-learn
scipy
sentencepiece
seqio
seqio-nightly
six
soupsieve
t5
tabulate
tensorboard
tensorboard-data-server
tensorflow
tensorflow-datasets
tensorflow-estimator
tensorflow-hub
tensorflow-io-gcs-filesystem
tensorflow-metadata
tensorflow-text
tensorstore
termcolor
tfds-nightly
threadpoolctl
tokenizers
toml
toolz
tqdm
transformers
typing-extensions
tzdata
urllib3
werkzeug
wheel
wrapt
zipp
setuptools
```
