### ISSUE TITLE
Published proof of IMO 2015 P3 is incorrect because ∠GMD != ∠GO2D

### ISSUE THREAD

**Issue by qria** [google-deepmind/alphageometry#7]
There's an error in the proof of IMO P3, in Fig1.f [1] and Step 26. of the full proof in supplimentary material[2], which it states that ∠GMD = ∠GO2D, which is incorrect. It should be ∠GMD + ∠GO2D = π. I am trying to follow its logic but I cannot parse what it is trying to do at Step 25. It has the right idea of O2 being on the nine point circle though.

[1]: https://www.nature.com/articles/s41586-023-06747-5/figures/1
[2]: https://storage.googleapis.com/deepmind-media/DeepMind.com/Blog/alphageometry-an-olympiad-level-ai-system-for-geometry%20/AlphaGeometry%20solution.pdf

**Comment by qria** [comment]
Nevermind, looks like it is using a directed angle. Sorry about that.

**Comment by trand2k** [comment]
same in IMO 2004 P1 at step 25, it looks like using a directed angle . right? 
![image](https://github.com/google-deepmind/alphageometry/assets/53207542/1f5f62eb-f056-4bbf-85cd-0096e36dd39d)

**Comment by Jerry-Master** [comment]
Yeah, in the original DD article they define full-angles equality. Two angles are equal if you can rotate the lines forming them and you end up with parallel lines. This makes an angle and its adjacent equal under this definition.
