### ISSUE TITLE
Wrong Rule of Equal Inscribed Angle

### ISSUE THREAD

**Issue by michael753-yen** [google-deepmind/alphageometry#97]
Here is the problem in nature language:
There is a square ABCD with E as the intersection of its diagonals. F is a point on AD. Let G be a circle that passes through A, P, and F,  intersects AC at Point H. 
translated into geometric language
`a b c d = isquare a b c d; p = on_line p a c, on_line p b d; e = on_line e a d; o = circle o a e p; f = on_circle f o a, on_line f a b ? cong d e a f`
![15603](https://github.com/google-deepmind/alphageometry/assets/57590758/ae90795e-5795-4db6-9d9e-2e4277c720ce)
alphageometry's proof is as following:
```
001. GA = GF [07] & GH = GA [10] & GF = GE [08] ⇒  A,H,E,F are concyclic [11]
002. A,H,E,F are concyclic [11] ⇒  ∠AHE = ∠AFE [12]
.....
```
Obviously, the 002 step is already wrong, it should be like  `∠AHE+∠AFE=180°` rather than `∠AHE = ∠AFE`‧ 

I've tried to modify the rules.txt, but it doesn't work at all.
Is there any way to fix it?

**Comment by Noxlgoldi** [comment]
The program uses directional angles you can look that up on wikipedia

**Comment by michael753-yen** [comment]
It has nothing to do with directional angle.
(here directional angle means `360°-∠AHE`)
`∠BHE = ∠AFE` is right, but how can `∠AHE` represents `∠BHE`?

**Comment by szhang99** [comment]
As [Noxlgoldi](https://github.com/Noxlgoldi) said, this is correct, you can assume this one and follow all the logic, you will see it is correct.

**Comment by michael753-yen** [comment]
@szhang99 yeah, your're right.
`003. A,D,F are collinear [06] & B,A,H are collinear [09] & ∠AHE = ∠AFE [12] ⇒  ∠DFE = ∠AHE [13]`
It got back on track immediately at the next step.
So, maybe I'll just ignore it?

**Comment by michael753-yen** [comment]
@szhang99 thanks a lot! The book you mentioned is very helpful. Btw, I'm a Taiwanese student but I have never heard of "directed angle". Is it a common sense to you guys?
